name: Run Ski News Agent

on:
  schedule:
    - cron: '0 3 * * *' # Каждый день в 6:00 утра по Москве
  workflow_dispatch: # Позволяет запускать вручную кнопку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Проверяем файлы
      uses: actions/checkout@v4

    - name: Настраиваем Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Устанавливаем библиотеки
      run: |
        pip install openai

    - name: Запускаем ИИ-агента
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python agent.py

    - name: Принудительно сохраняем index.html на сайт
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        git add index.html
        git commit -m "Автоматическое обновление [ИИ-Агент]" --allow-empty
        git push origin main || git push origin master
